---
  - name: CICD deployment Script
    hosts: all
    vars:
      token: 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
      username: naveen5758
      repo_name: sample_project
    tasks: 
      - name: Cloning the code from git
        git:
          repo: https://{{token}}@github.com/{{username}}/{{repo_name}}.git
          dest: /tmp/project/

      - name: Installing the java version
        become: yes
        yum:
          name: https://corretto.aws/downloads/latest/amazon-corretto-11-x64-linux-jdk.rpm
          state: present

#      - name: Installing the maven 
#        become: yes
#        shell : | 
#          sudo apt install maven -y 

#      - name: check the version 
#        shell: | 
#          mvn --version 
#        register: data


#      - name: Build the Project 
#        shell: |
#          cd /tmp/project/
#          mvn clean package 
#        register: maven_op

#      - name: print the maven o/p
#        debug: 
#          var: maven_op

      - name: installing the tomcat
        become: yes 
        unarchive:
          src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.71/bin/apache-tomcat-9.0.71.tar.gz
          dest: /tmp/
          remote_src: yes
        ignore_errors: True

      - name: renaming the tomcat folder
        become: yes
        shell: |
          mv /tmp/apache-tomcat-9.0.71 /tmp/tomcat
          chmod -R 777 /tmp/tomcat
          chown -R ansadmin:ansadmin /tmp/tomcat
          cp /home/ansadmin/*.war /tmp/tomcat/webapps/
          sh /tmp/tomcat/bin/startup.sh
